# pulling httpd image from docker hub
  - name: pull httpd image
    command: docker pull httpd
# launching a new container with httpd image
# see below we are binding /data/workspace/website/ to htdocs
# remember we have to create a job in jenkins with name website only
  - name: run httpd container
    command: docker run -dit --name webserver -p 80:80 -v /data/workspace/website/:/usr/local/apache2/htdocs/ httpd