# pulling jenkins image from docker hub
  - name: pull jenkins image
    command: docker pull jenkins/jenkins
# launching a new container jenkins image 
  - name: run jenkins container
    command: docker run -dit --name jenkins -u root -p 8080:8080 -v /data/:/var/jenkins_home jenkins/jenkins
# making a workspace and job directory because this directory are created when we create a job,
# but we want to bind /data/workspace/website to htdocs
  - name: make workspace directory for jenkins job
    file:
      path: /data/workspace/website
      state: directory