name: "Server configuration"

# on: 
#   workflow_dispatch:
#     inputs:
#       logLevel:
#         description: 'Log level'     
#         required: true
#         default: 'warning'
#       tags:
#         description: 'Test scenario tags'  

on: push

jobs:
  deploy:
    name: Deploy to EC2 on click
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy to WebServer
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ubuntu
          TARGET: /home/ubuntu
          
      - name: Install Ansible
        run:  sudo apt-get install -y ansible

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          # Required, playbook filepath
          playbook: provision_web_server.yml
          # Optional, directory where playbooks live
          directory: ./infrastructure/ansible
          key: ${{env.EC2_SSH_KEY}}


#TODO: DOCKER + PROMETUESZ