name: "Server configuration"

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  

# on: push

jobs:
  deploy:
    name: Deploy to EC2 on click
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy to WebServer
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ubuntu
          TARGET: /home/ubuntu

      - name: Ansible configuration
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.EC2_SSH_KEY }}
          host: ${{ secrets.HOST_DNS }}
          username: ubuntu
          port: 22 
          script:  |
            sudo apt update &&\
             sudo apt-get install -y ansible &&\
              cd infrastructure/ansible &&\
               ansible-playbook --connection=local provision_web_server.yml


#TODO: DOCKER + PROMETUESZ