name: Spring Boot tests

on: push

jobs:
  microservices:
    runs-on: ubuntu-latest

    steps:
      - name: Download repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Test place-service
        run: cd "Spring Boot/microservices/place-service/" && make test
        
      - name: Test distance-service
        run: cd "Spring Boot/microservices/distance-service/" && make test
        
      - name: Test route1-service
        run: cd "Spring Boot/microservices/route1-service/" && make test
        
      - name: Test route2-service
        run: cd "Spring Boot/microservices/route2-service/" && make test

  monolith:
    runs-on: ubuntu-latest

    steps:
      - name: Download repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Test monolith
        run: cd "Spring Boot/monolith/" && make test