name: Spring Boot tests

on: push

jobs:
  microservices:
    runs-on: ubuntu-latest

    steps:
      - name: Download repository
        uses: actions/checkout@v2

      - name: Build docker environment
        run: docker-compose -f docker-compose-spring-boot-microservices.yml up --build -d

      - name: Run e2e tests
        run: pip install -r .github/e2e/requirements.txt && python -m pytest --timeout=10 .github/e2e/