name: tests

on: push

jobs:
  unit_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Download repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Test place-service
        run: cd place-service/ && mvn clean test
        
      - name: Test distance-service
        run: cd distance-service/ && mvn clean test